### ISSUE TITLE
Warn about anisotropic permittivity

### ISSUE THREAD

**Issue by elinscott** [epfl-theos/koopmans#137]
Add a warning for anisotropic systems that the permittivity is assumed to be isotropic (as a stop-gap before this is properly resolved with #84 )

**Comment by elinscott** [comment]
I think what we want here is

```
from ase.spacegroup.symmetrize import check_symmetry
dataset = check_symmetry(self.atoms, 1.0e-6, verbose=True)
dataset['pointgroup_number']
```

N.B. will require us to add `pyspglib` to `requirements.txt`

**Comment by elinscott** [comment]
According to https://en.wikipedia.org/wiki/List_of_space_groups it looks like then all we need to do is check if the pointgroup number is 195-230

**Comment by nscolonna** [comment]
Agree! Just double checked also on the Bilbao crystallographic server:
https://www.cryst.ehu.es/cgi-bin/cryst/programs/tensor.pl
If you ask for the structure of the dielectric tensor (choose it under "equilibrium tensor") for all the point groups, the only one that is diagonal and has only 1 independent coefficient is for the 23 m-3 432 -43m m-3m point groups (in the Hermann–Mauguin notation), which correspond exactly to 195-230 (from wikipedia).
