### ISSUE TITLE
Restructure json input files to improve consistency of Workflow initialization

### ISSUE THREAD

**Issue by elinscott** [epfl-theos/koopmans#167]
Currently there are several issues with the json input file:

1. the `workflow` block is bloated, with too many keywords
2. the input file structure does not mirror the structure of the `Workflow` object inside of python. This results in some tortured logic inside the code and the inconsistencies can surprise users -- they'd almost have to learn two different conventions
3. the `setup` block has no analogue inside python -- it's just magic used when reading the json input file

I also really don't like the name `master_calc_params` and I would like to change this to be more simple.

I propose that we restructure the format of the input file as follows:
```
{
  "workflow": { ... },
  "atoms": { ... }, # replaces the setup block, called "atoms" in line with ASE. Accepts ibrav and celldms
  "kpoints": { ... }, # moved from setup block
  "pseudopotentials": {" ... "} # moved from setup block
  "calculators": {"universal": { ... }, # replaces the parts of the setup block where one could set e.g. ecutwfc for kcp and pw simultaneously 
                  "kcp": { ... },
                  "pw": { ... }
                 },
  "image_correction": { ... } # a few keywords moved from the "workflow" block that don't really have anything to do with the workflow per se
  "plotting": { ... }
``` 

One issue with renaming `master_calc_params` as `calculators` is that we have a nameclash with the module `koopmans.calculators`. Maybe `calculator_parameters` is a good alternative?

**Comment by elinscott** [comment]
Because I would like to avoid changing the input file format after the code release, I have added this to the v1.0 release milestone

**Comment by schuyann** [comment]
In the spirit of the second point (not having to learn two different conventions), I think it would be nice to aim towards solutions, where the pythonic way of generating input files, e.g.:
```
wf = workflows.SinglepointWorkflow(input_dict)
write(wf, 'test.json')
```
results in very concise input files (with as little redundancy as possible) that are as close as possible to `json`-files from tutorials etc. 
Moreover, I think it would be nice if the dictionary `input_dict` is in structure very similar to the structure of the `json` file. 
I think by removing the `setup`-block we already get much closer to this goal. 
Maybe there is also a way to 
1. specify the `universal`-block also when generating input files with the pythonic way
2. recover the `universal` block, e.g. with some additional logic in the `toinputjson`-method

?
