### ISSUE TITLE
kcp.x error

### ISSUE THREAD

**Issue by similt** [epfl-theos/koopmans#219]
In my koopman work flow , I am getting error, "Out Of Memory" while running kcp.x, . I increased the number of nodes to 20, but the error is same. I see that super cell size is nearly 25A*25A*25A in length in cp input. Wannierization completed as shown below. Do you think is there any other reason for the job failure. 

  Initialization of density and variational orbitals
  ==================================================

   Wannierization
   ==============
    Running wannier/scf... done
    Running wannier/nscf... done
    Running wannier/block_1/wann_preproc... done
    Running wannier/block_1/pw2wan... done
    Running wannier/block_1/wann...CalculatorNotConvergedWarning: /lustre/scratch/thoms0a/qe/koopman/Rb3InCl6/koopman-input/init/wannier/block_1/wann did not converge; proceed with caution
 done
    Running wannier/block_2/wann_preproc... done
    Running wannier/block_2/pw2wan... done
    Running wannier/block_2/wann...CalculatorNotConvergedWarning: /lustre/scratch/thoms0a/qe/koopman/Rb3InCl6/koopman-input/init/wannier/block_2/wann did not converge; proceed with caution
 done

   Folding to supercell
   --------------------
    Running block_1/w2kcp... done
    Running block_2/w2kcp... done
   Running init/dft_dummy...UserWarning: Small box parameters "nrb" not provided in input: these will be automatically set to safe default values. These values can probably be decreased, but this would require convergence tests.
   Estimated real mesh dimension (nr1, nr2, nr3) = 240 225 250
   Small box mesh dimension (nr1b, nr2b, nr3b) = 30 30 30

 failed

**Comment by nscolonna** [comment]
Hi, could you please provide the json input file and the submission scripts for us to carefully check?
I think this could well be not enough RAM issue. We are aware of the high RAM demanding of the supercell implementation (kcp.x) and working to find a solution. 
For the moment you can try to reduce the number of tasks per nodes (while keeping constant the number of nodes), or use the PC implementation of KI by switching from `dscf` to `dfpt` in your input file. This is a simplified KI implementation but less time and memory demanding for extended systems.

**Comment by similt** [comment]
Thanks. reducing the number of tasks per node solved the issue. I have another question which I will ask in google group.

**Comment by nscolonna** [comment]
Happy to hear that this works. I'm going to close this issue.
