### ISSUE TITLE
Automatically set nr1-3b

### ISSUE THREAD

**Issue by elinscott** [epfl-theos/koopmans#71]
The parameters `nr1`-`3b` specify some technical parameters related to FFTs. `kcp.x` will crash if these keywords are not provided, but we do not want a user to need to know what this is and how to set it.

We should set this automatically. According to an [old QE manual](http://www.ehu.eus/sgi/ARCHIVOS/espresso) there is a simple expression for the value to set this to:

```
nr1b = (2 × rcut)/Lx × nr1
```

(likewise for `nr2b` and `nr3b`). Among other things this requires us to know...

- the largest cutoff radius `rcut` of all the pseudopotentials in the system. This information is contained in the pseudopotentials under the `<PP_NONLOCAL><PP_BETA>` or `<PP_BETA.X>` fields in a UPF file. We will need to survey existing UPF files to make sure we can reliably extract this variable.
- `nr1`-`3`. These can be set automatically using equations contained in QE -- possibly

```
         dfft%nr1 = int ( sqrt (gcutm) * sqrt (at(1, 1)**2 + at(2, 1)**2 + at(3, 1)**2) ) + 1
```

(taken from `FFTXlib/fft_types.f90`). Need to double-check this

**Comment by nscolonna** [comment]
Setting nrb as nr by default at the workflow level is more difficult than expected. Beside the formula above (see Edward's comment dated 30 sept 2021), there is an extra step where a "good" fft dimension that is larger than and the closest to the one provided by the formula above is selected (see `good_fft_order` inside `/kcp/Modules/fft_scalar.f90` called by `real_space_grid_init` inside `kcp/Modules/griddim.f90`.
Not too difficult but we need to mirror the fortran code that decides which is the closest "good" fft_dimenion (`good_fft_order` mentioned above)

**Comment by nscolonna** [comment]
For reference: the system dependent setting of the good fft grid is triggered by the -D__LINUX_ESSL (or -D__ESSL) precompilation flag (see `Modules/fft_scalar.f90`). As far as I understand from the `/install/configure` file this should appear as an extra flag in the  `DFLAGS` variable inside make.sys. I'm going use this information to code the system-dependent setting of the good FFT grid in the Workflow
