### ISSUE TITLE
Create workflow to generate projected DOS to help assist choosing wannier projections

### ISSUE THREAD

**Issue by elinscott** [epfl-theos/koopmans#91]
Currently when performing Koopmans calculation the first step is to work out appropriate wannier orbitals. This typically involves looking at the pDOS.

This is done manually at present but it would be good to support this within `koopmans`

The idea would be to extend the `singlepoint` workflow with `functional = dft` such that it generates pDOS that are easy to plot.

**Comment by degennar** [comment]
> @degennar is this a good project for you to tackle?

Sorry I had completely missed that. Sure I'll take care of this.
